### ISSUE TITLE
WPA3 setup without CA validation

### ISSUE THREAD

**Issue by stephenmullenss** [datalogic/scan2deploy-studio#9]
So just trying to set up a WPA3-Enterprise network connection without a CA validation "do not validate" but I don't seem to be managing the setup of this, If left blank on setup device it still says "please select". Any advice?

**Comment by bronson-mock** [comment]
Hi, could you please provide the following information:

- Scan2Deploy Studio version
- Target device info (model, Android OS, S2D Agent version)

Are you experiencing this issue during the profile setup, or while trying to connect to the network on the device?

**Comment by stephenmullenss** [comment]
Hi 
The Scan2Deploy Studio Version 1.9.0 and the device is Skorpio X5, android version 10 and S2D Agent V2.2.3.

When adding a WIFI connection with the S2D Studio there's no option for "do not validate" for the CA certification.
![Screenshot 2023-11-15 092412](https://github.com/datalogic/scan2deploy-studio/assets/150006764/a7a3e635-6657-4ac9-956d-8526a2f882e9)

I'm having the issue with both, on the initial setup its unable to connect to WIFI and establish a IP address. When on the device the WIFI it is showing as "please select" as if no CA validation option has been selected. Needing to have this with "do not validate" but there seems to be no option for this

**Comment by bronson-mock** [comment]
The "do not validate" option will be available in the next official release (v2.0.0) of Scan2Deploy Studio. If you would like immediate access to this option, you can download the latest beta version found in the [releases](https://github.com/datalogic/scan2deploy-studio/releases) section. Please note that the beta is a pre-release version that is in the late stages of the development/test cycle, but is not an official release.

However, I believe that the network configuration should succeed within your scenario since "do not validate" should be used on Android 10 if no CA certificate is provided. Are you able to delete and then add the network manually through the Android UI to test connectivity? If not, I would recommend verifying that the Identity and Password information is correct for the network. 

As a side note, if you are using the Android settings UI to view the network details, it appears that the UI does not load the configured CA certificate value on various Android versions and will always show "please select" regardless of the value. So unfortunately this does not seem to be a reliable method for verifying the CA certificate value on saved networks.

**Comment by stephenmullenss** [comment]
Great stuff I have managed to download the latest beta release (2.0.0-beta.1) and does have the "do not validate" option. When editing the old profile it was still unsuccessful but worked like a dream with the new profile. I have found that I had to make a new profile to have access to all the new options rather than editing a pre-existing profile instead.

**Comment by stephenmullenss** [comment]
manged to get the pre-exiting to connect to some degree, the second WIFI connection has issues but on the new profile its fine with both connection. Realise the limited setting were due to incorrect android selected though.
